# Generated by Django 4.0.6 on 2022-08-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longURL', models.URLField(max_length=300)),
                ('shortURL', models.CharField(max_length=8)),
            ],
        ),
    ]
